[project]
name = "MeshTBD"
version = "0.1.0"
description = "Script-driven anatomical mesh processing and cross-library interoperability for personalized 3D-printable cast geometry."
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "bpy>=4.5.1",
    "numpy>=1.26.4",
    "open3d>=0.19.0",
    "plyfile>=1.1.2",
    "polyscope>=2.6.0",
    "pymeshlab>=2023.12.post3",
    "pyvista>=0.46.1",
    "scipy>=1.16.1",
    "trimesh>=4.9.0",
]

[tool.uv]
required-environments = [
	"sys_platform == 'linux' and platform_machine == 'x86_64' and python_version == '3.11'"
]

[dependency-groups]
dev = [
    "inspect-it>=0.3.2",
    "ipykernel>=7.2.0",
    "ty>=0.0.15",
]
